### ISSUE TITLE
[design] Исправление на странице Товара.

### ISSUE THREAD

**Issue by griphon56** [griphon56/septic78#23]
1) В блоке "Можно подключить", исправить верстку https://www.screencast.com/t/PQ0gyvZJnbJ
2) Поправить стили для https://www.screencast.com/t/qX8PUH7CMR
3) Выравнивание по правому краю https://www.screencast.com/t/NYNjMvDSGcR
4) Убрать пустое пространство, изменить размер картинки https://www.screencast.com/t/y6UjpUCwy

**Comment by alinamorneva** [comment]
![image](https://user-images.githubusercontent.com/26758737/43085242-2663710c-8ea3-11e8-9a2a-f11c048d1384.png)
Выравнять по правому краю

**Comment by alinamorneva** [comment]
393502841d2d7271825e8b277d370dcac10da3d4

**Comment by alinamorneva** [comment]
06ce8641c0a31e545b2ad616e942867215daefd3
