### ISSUE TITLE
[mobile] Сделать Футер сайта.

### ISSUE THREAD

**Issue by griphon56** [griphon56/septic78#35]

**Comment by alinamorneva** [comment]
99fd8bd64f0ba2de97ed8eac0d1fca1f559bb432

**Comment by alinamorneva** [comment]
67542f0e007e1740a9ceb21d54996c16043f11d7

**Comment by alinamorneva** [comment]
cd5c9f12c423a83c348b417e7461d73e2d7ec8e8 исправила

**Comment by alinamorneva** [comment]
92e30f69b958a2e685f6c0a38256acd3ee4e6603

**Comment by griphon56** [comment]
done
