### ISSUE TITLE
[mobile] Сделать страницу Услуги.

### ISSUE THREAD

**Issue by griphon56** [griphon56/septic78#38]

**Comment by alinamorneva** [comment]
e11d1bb4b2b7bac8c924912244c4d1e925cff584

**Comment by griphon56** [comment]
Срелочки отодвинуть от краёв

**Comment by alinamorneva** [comment]
49f50a19d7600afa3d328867b36c3b5f8b8309c6 стрелки
2 - не могу исправить то чего не вижу

**Comment by griphon56** [comment]
done.
