### ISSUE TITLE
[mobile] Сделать страницу О компании.

### ISSUE THREAD

**Issue by griphon56** [griphon56/septic78#39]

**Comment by alinamorneva** [comment]
f9f74fde79eb4e15898374b2b2c909ac309fef19

**Comment by griphon56** [comment]
Убрать картинку https://www.screencast.com/t/nGUPGZ7YKLBS

**Comment by alinamorneva** [comment]
18ac044cd0ca0212a7ab5a6ada96ebaf8952f2d3
